/* eslint-disable import/prefer-default-export */
/* eslint-disable import/prefer-default-export */
import { MissionDifficulty, QualityLevel } from '../enums';

export const missionsInfo: {
  name: string;
  desc: string;
  quality: QualityLevel;
  difficulty: MissionDifficulty;
}[] = [
  {
    name: '清理老鼠',
    desc: '酒馆地窖里出现了一群老鼠，它们正在破坏储存的食物。需要有人帮忙清理。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '采集药草',
    desc: '药剂师需要一些常见的药用植物，这些植物生长在镇子附近的草地上。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '驱赶野兔',
    desc: '农夫的菜园被野兔侵扰，需要帮忙驱赶这些调皮的小家伙。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '送信任务',
    desc: '需要有人将一封普通信件送到邻镇，路途平坦安全。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '寻找丢失的羊',
    desc: '牧羊人的一只羊走失了，很可能就在附近的草地上。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '搬运货物',
    desc: '商人需要帮手将一批货物从仓库搬运到店铺。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '巡逻果园',
    desc: '果农需要人手帮忙巡逻果园，防止小偷偷水果。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '清扫马厩',
    desc: '马厩需要打扫，工作虽然简单但很重要。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '收集蘑菇',
    desc: '厨师需要一些新鲜的蘑菇，它们生长在镇外的小树林里。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '修补篱笆',
    desc: '农场的篱笆需要修理，材料都已准备好。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '驱赶野狗',
    desc: '镇子里出现了几只流浪狗，需要有人把它们赶到镇外。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '寻找丢失的工具',
    desc: '铁匠的学徒把一些工具弄丢了，需要帮忙在工坊附近找找。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '清理杂草',
    desc: '城墙根部长满了杂草，需要有人帮忙清理。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '运送面粉',
    desc: '面包房需要有人帮忙把面粉从磨坊运来。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '寻找迷路的孩子',
    desc: '一个小孩在镇子里玩耍时迷路了，需要帮忙找到他。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '照看羊群',
    desc: '牧羊人生病了，需要有人帮忙照看羊群一天。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '清理水渠',
    desc: '农田的灌溉水渠被落叶堵塞，需要疏通。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '巡查谷仓',
    desc: '粮仓管理员需要帮手检查谷仓是否有老鼠出没。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '帮工酿酒',
    desc: '酒馆需要帮手搬运和清洗酿酒用的木桶。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '整理货架',
    desc: '杂货店需要整理和清点商品，工作轻松但要仔细。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '巡逻码头',
    desc: '港口管理员需要临时帮工维持码头秩序，工作内容主要是巡视和登记。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '喂养家禽',
    desc: '农场主的女儿扭伤了脚，需要有人帮忙喂养鸡鸭一天。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '整理书架',
    desc: '图书馆需要帮手整理和清点书籍，要求识字且工作仔细。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '修补渔网',
    desc: '渔民需要帮手修补破损的渔网，工作简单但耗时。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '采集蜂蜜',
    desc: '蜂农需要帮手收集野生蜂蜜，需要小心蜜蜂蛰咬。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.NORMAL,
  },
  {
    name: '清点库存',
    desc: '商会需要人手帮忙清点仓库货物，要求识字和会基础计算。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '寻找丢失的戒指',
    desc: '一位老妇人在市场丢失了她的铜戒指，愿意支付酬劳寻找。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '搬运木材',
    desc: '木匠需要帮手将新到的木材从城门搬运到工坊。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '清洁街道',
    desc: '城市卫生官需要临时工清扫主街道，为即将到来的节日做准备。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '照看病人',
    desc: '医馆需要人手照看一些轻症病人，工作内容主要是端水送药。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '分发传单',
    desc: '新开张的杂货铺需要人在街上分发宣传传单。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '看守果园',
    desc: '果农需要人手看守即将成熟的水果，防止小偷光顾。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '清理鸽舍',
    desc: '信鸽驿站需要打扫鸽舍，工作虽然不太体面但报酬尚可。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '引导游客',
    desc: '城市观光处需要向导为游客介绍城市景点，要求熟悉本地。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '搬运酒桶',
    desc: '酒馆进了一批新酒，需要帮手将酒桶搬运到地窖。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '修补围墙',
    desc: '牧场的石头围墙有些损坏，需要帮手进行简单修补。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.NORMAL,
  },
  {
    name: '清理池塘',
    desc: '城市公园的池塘需要清理淤泥和杂物。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '照看店铺',
    desc: '杂货店老板需要外出采购，需要人手临时照看店铺半天。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '寻找宠物',
    desc: '一位贵妇人的宠物猫走丢了，需要在城里帮忙寻找。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '整理仓库',
    desc: '商会仓库需要整理和分类货物，工作繁琐但不费力。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '捕捉流浪猫',
    desc: '城市管理员需要有人帮忙捕捉并安置街上的流浪猫，要求对待动物要温柔。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '协助织布',
    desc: '织布工坊需要帮手整理原料和清洁织布机，工作轻松但要细心。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '搬运石料',
    desc: '石匠需要帮手将石料从采石场运到工作坊，体力活。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '清理烟囱',
    desc: '面包房的烟囱需要清理，工作虽然会弄脏衣服但报酬不错。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '修剪花园',
    desc: '贵族府邸需要园丁帮手修剪花园的灌木，要求熟悉园艺。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '巡查下水道',
    desc: '城市维护部门需要人手检查下水道是否堵塞，工作环境较差但报酬优厚。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.NORMAL,
  },
  {
    name: '照看孤儿',
    desc: '教会孤儿院的修女生病了，需要人手帮忙照看孤儿一天。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '清点药材',
    desc: '药剂师需要帮手整理和清点药材库存，要求认识基础药材。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '维护路灯',
    desc: '城市守卫需要人手检查和更换街道上的油灯，确保夜晚照明。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '喂养马匹',
    desc: '马厩老板需要临时工照料马匹，包括喂食和刷洗。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '清理地窖',
    desc: '酒馆的地窖需要大扫除，搬运酒桶和清理杂物。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '协助铁匠',
    desc: '铁匠铺需要学徒帮忙整理工具和保持炉火，无需专业技能。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '巡查果树',
    desc: '果园主人需要人手检查果树是否有病虫害，要求对果树有基本了解。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '搬运渔获',
    desc: '渔民需要帮手将今天的渔获从码头运送到市场。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '清点羊毛',
    desc: '纺织作坊需要整理新到的羊毛，分类并记录数量。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '维护水井',
    desc: '城市需要人手清理和维护公共水井，确保饮用水安全。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.NORMAL,
  },
  {
    name: '照看老人',
    desc: '一位富商需要人照顾生病的父亲一天，主要是陪伴和照料起居。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '清理谷仓',
    desc: '农场主需要帮手清理谷仓，为新收获的粮食腾出空间。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '修补衣物',
    desc: '裁缝铺需要帮手修补一批普通衣物，要求会基础针线活。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '整理草药园',
    desc: '药剂师需要人手帮忙打理草药园，包括浇水和除草。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '清扫神殿',
    desc: '当地神殿需要帮手打扫地面和整理供品，工作简单但需要恭敬。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '整理渔具',
    desc: '渔具店需要帮手整理和修补各种渔具，要求了解基本渔具。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '搬运木柴',
    desc: '铁匠铺需要人手将新到的木柴堆放整齐，纯体力活。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '清洗地毯',
    desc: '富商家需要帮工清洗一批贵重地毯，要求小心仔细。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '照看花圃',
    desc: '城主府的花匠需要帮手照料珍贵的花卉，包括浇水和施肥。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '巡查市场',
    desc: '市场管理员需要帮手维持秩序，防止小偷和欺诈行为。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '清点陶器',
    desc: '陶器店需要整理新到的一批陶器，要求轻拿轻放。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '帮厨打杂',
    desc: '酒馆厨房需要帮工准备食材和清洗餐具。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '整理马具',
    desc: '马厩需要人手清洁和整理各种马具，要求认识基本马具。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '搬运布匹',
    desc: '布商需要帮手将一批布匹从码头运到店铺。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '清理鱼塘',
    desc: '渔场主人需要帮手清理养鱼池塘，工作脏累但报酬不错。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.NORMAL,
  },
  {
    name: '整理谷物',
    desc: '粮仓管理员需要帮手分类存放新到的谷物。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '修补工具',
    desc: '农具店需要帮手修理一批农具，要求会使用简单工具。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '清扫广场',
    desc: '城市需要清洁工打扫中央广场，为即将举行的集市做准备。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '照看幼童',
    desc: '托儿所需要临时工照看幼童，要求有耐心和爱心。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '整理皮革',
    desc: '皮革店需要帮手整理和分类各种皮革，要求了解基本皮革品质。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '搬运家具',
    desc: '一户搬家的居民需要帮手搬运家具，纯体力活。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '清理水沟',
    desc: '城市卫生官需要人手清理街道的排水沟，工作环境较差。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '整理货物',
    desc: '码头仓库需要分类整理新到的货物，要求识字。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '喂养牲畜',
    desc: '农场需要帮手喂养和照料各种牲畜一天。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '清点布匹',
    desc: '布庄掌柜需要帮手清点新到的布匹，要求认识基本布料种类。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '整理工具房',
    desc: '城市维修处需要整理各类工具，要求熟悉基本工具的名称。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '搬运面粉',
    desc: '面包坊需要将新磨好的面粉从磨坊搬运到店里，体力活。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '清洁马车',
    desc: '马车行需要人手清洗几辆出租马车，工作简单但要仔细。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '整理药柜',
    desc: '药房需要整理药材柜台，要求认识常见药材。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '除草任务',
    desc: '城墙外的护城河边杂草丛生，需要人手清理。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '搬运陶器',
    desc: '陶器店新到了一批易碎品，需要帮手小心搬运。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '整理羊圈',
    desc: '牧场主需要清理羊圈，铺新的干草。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '清洁店面',
    desc: '杂货店需要全面清洁，包括擦拭货架和打扫地面。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '分拣蔬果',
    desc: '水果摊主需要将新到的水果分类摆放，要求认识常见水果。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '维护路标',
    desc: '城市需要人手检查和修补路标，确保标识清晰。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '整理渔网',
    desc: '渔民需要帮手整理和晾晒渔网，防止网具腐烂。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '搬运木材',
    desc: '木匠铺需要将新购的木材搬运到工坊后院。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '清理鸡舍',
    desc: '家禽贩子需要打扫鸡舍，更换垫料。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '整理账本',
    desc: '商行需要整理旧账本，要求识字会算数。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '打扫茶馆',
    desc: '茶馆掌柜需要帮手打扫店面，整理桌椅。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '清点蜡烛',
    desc: '蜡烛作坊需要清点库存，分类存放。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '整理谷仓',
    desc: '农户需要帮手整理谷仓，清理鼠害。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '搬运酒水',
    desc: '酒馆需要将一批新酒搬运到地窖存放。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '修补围栏',
    desc: '牧场的木栅栏有多处损坏，需要简单修补。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '巡逻码头',
    desc: '港口管理员需要临时帮工维持码头秩序，工作内容主要是巡视和登记。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '喂养家禽',
    desc: '农场主的女儿扭伤了脚，需要有人帮忙喂养鸡鸭一天。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '整理书架',
    desc: '图书馆需要帮手整理和清点书籍，要求识字且工作仔细。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '修补渔网',
    desc: '渔民需要帮手修补破损的渔网，工作简单但耗时。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '采集蜂蜜',
    desc: '蜂农需要帮手收集野生蜂蜜，需要小心蜜蜂蛰咬。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.NORMAL,
  },
  {
    name: '清点库存',
    desc: '商会需要人手帮忙清点仓库货物，要求识字和会基础计算。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '寻找丢失的戒指',
    desc: '一位老妇人在市场丢失了她的铜戒指，愿意支付酬劳寻找。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '搬运木材',
    desc: '木匠需要帮手将新到的木材从城门搬运到工坊。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '清洁街道',
    desc: '城市卫生官需要临时工清扫主街道，为即将到来的节日做准备。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '照看病人',
    desc: '医馆需要人手照看一些轻症病人，工作内容主要是端水送药。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '分发传单',
    desc: '新开张的杂货铺需要人在街上分发宣传传单。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '看守果园',
    desc: '果农需要人手看守即将成熟的水果，防止小偷光顾。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '清理鸽舍',
    desc: '信鸽驿站需要打扫鸽舍，工作虽然不太体面但报酬尚可。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '引导游客',
    desc: '城市观光处需要向导为游客介绍城市景点，要求熟悉本地。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '搬运酒桶',
    desc: '酒馆进了一批新酒，需要帮手将酒桶搬运到地窖。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '修补围墙',
    desc: '牧场的石头围墙有些损坏，需要帮手进行简单修补。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.NORMAL,
  },
  {
    name: '清理池塘',
    desc: '城市公园的池塘需要清理淤泥和杂物。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '照看店铺',
    desc: '杂货店老板需要外出采购，需要人手临时照看店铺半天。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '寻找宠物',
    desc: '一位贵妇人的宠物猫走丢了，需要在城里帮忙寻找。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '整理仓库',
    desc: '商会仓库需要整理和分类货物，工作繁琐但不费力。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '城市巡查',
    desc: '城市治安队需要临时巡查员，维持市场和街道的秩序。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '药材鉴定',
    desc: '药房需要帮手鉴别一批新到的药材，要求对常见药材有深入了解。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.NORMAL,
  },
  {
    name: '驯服野马',
    desc: '马场需要经验丰富的驯马师驯服一批新捕获的野马。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.HARD,
  },
  {
    name: '危险货物押运',
    desc: '商会需要经验丰富的押运员护送一批危险的炼金材料。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EPIC,
  },
  {
    name: '猛兽捕获',
    desc: '马戏团需要捕获一头成年狮子，要求活捉且尽量不伤害它。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.LEGENDARY,
  },
  {
    name: '教授剑术',
    desc: '贵族需要剑术教师指导他的子女学习基础剑术。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '调查盗窃',
    desc: '商铺遭遇连环盗窃，需要经验丰富的调查员追查真相。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.NORMAL,
  },
  {
    name: '驱除害虫',
    desc: '粮仓出现大量魔法变异的害虫，需要有经验的除虫师处理。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.HARD,
  },
  {
    name: '押送要犯',
    desc: '城市守卫需要可靠的押送员将一名危险罪犯押送到邻城。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EPIC,
  },
  {
    name: '驯服魔宠',
    desc: '魔法师需要驯兽师帮忙驯服一只暴躁的狮鹫幼崽。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.LEGENDARY,
  },
  {
    name: '训练新兵',
    desc: '城防队需要有经验的战士训练一批新招募的守卫。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '医治瘟疫',
    desc: '城郊农场的牲畜染上怪病，需要经验丰富的兽医进行救治。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.NORMAL,
  },
  {
    name: '清除魔物',
    desc: '城市下水道出现了一群危险的魔化老鼠，需要经验丰富的猎手清除。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.HARD,
  },
  {
    name: '护送商队',
    desc: '一支载有贵重魔法物品的商队需要可靠的护卫穿越强盗频繁出没的区域。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EPIC,
  },
  {
    name: '捕获巨蛇',
    desc: '魔法研究所需要捕获一条罕见的魔化巨蛇，要求活捉且完好无损。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.LEGENDARY,
  },
  {
    name: '教导礼仪',
    desc: '新贵族家庭需要礼仪教师指导全家人贵族礼仪。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '调查诅咒',
    desc: '一户人家疑似被人下了诅咒，需要经验丰富的调查员查明真相。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.NORMAL,
  },
  {
    name: '狩猎魔狼',
    desc: '森林里出现了一群被魔法污染的狼群，需要熟练的猎人清除威胁。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.HARD,
  },
  {
    name: '运送魔药',
    desc: '炼金术士需要可靠的运送者将一批不稳定的魔药送往邻国。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EPIC,
  },
  {
    name: '降服魔像',
    desc: '一座失控的魔像正在城市郊外游荡，需要能工巧匠将其降服。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.LEGENDARY,
  },
  {
    name: '指导冶炼',
    desc: '铁匠铺需要经验丰富的工匠指导学徒们冶炼特殊金属。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '破解密文',
    desc: '商会需要密文专家破解一份可能涉及走私的密信。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.NORMAL,
  },
  {
    name: '探索遗迹',
    desc: '考古学会需要经验丰富的探险家调查新发现的古代遗迹。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.HARD,
  },
  {
    name: '护送贵族',
    desc: '一位重要贵族需要可靠的护卫队伍护送他穿越危险地区。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EPIC,
  },
  {
    name: '收服巨鹰',
    desc: '皇家猎场需要驯兽师捕获并驯服一只体型罕见的巨型猎鹰。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.LEGENDARY,
  },
  {
    name: '教授占卜',
    desc: '占星馆需要有经验的占卜师教导学徒基础占卜技巧。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '调查失踪',
    desc: '一名商人在城郊神秘失踪，需要经验丰富的调查员追查线索。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.NORMAL,
  },
  {
    name: '清除亡灵',
    desc: '古老墓地出现了一些低级亡灵生物，需要驱魔师清理。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.HARD,
  },
  {
    name: '护送圣物',
    desc: '教会需要可靠的护卫队伍护送一件重要圣物前往大教堂。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EPIC,
  },
  {
    name: '捕获石怪',
    desc: '魔法学院需要捕获一只稀有的活体石怪用于研究。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.LEGENDARY,
  },
  {
    name: '训练猎鹰',
    desc: '皇家猎场需要经验丰富的驯鹰师训练新捕获的猎鹰。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '调查诈骗',
    desc: '商会怀疑有人使用伪造的商会文书进行诈骗，需要经验丰富的调查员追查。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.NORMAL,
  },
  {
    name: '驱逐邪灵',
    desc: '一座古宅内出现了危险的邪灵，需要驱魔师进行处理。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.HARD,
  },
  {
    name: '护送魔法师',
    desc: '一位重要的魔法师需要可靠的护卫穿越充满危险的魔法荒野。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EPIC,
  },
  {
    name: '封印魔物',
    desc: '一头远古魔物即将从封印中苏醒，需要精通封印术的法师加固封印。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.LEGENDARY,
  },
  {
    name: '教授炼金',
    desc: '炼金术士需要助手教导学徒制作基础药水，要求熟悉炼金术。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '追查盗贼',
    desc: '一伙盗贼偷走了重要的魔法道具，需要经验丰富的追踪者追查其行踪。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.NORMAL,
  },
  {
    name: '猎杀魔兽',
    desc: '森林深处出现了一头危险的魔化野猪，需要熟练的猎人将其猎杀。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.HARD,
  },
  {
    name: '押运宝物',
    desc: '商会需要可靠的护卫押运一批珍贵的魔法宝石穿越盗贼横行的区域。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EPIC,
  },
  {
    name: '降伏魔龙',
    desc: '一头年幼的魔龙在山脉中出没，需要驯兽师将其活捉并驯服。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.LEGENDARY,
  },
  {
    name: '指导格斗',
    desc: '城市卫队需要武术教师指导新兵掌握基本的格斗技巧。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '调查走私',
    desc: '港口官员发现有人走私违禁魔法物品，需要调查员追查源头。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.NORMAL,
  },
  {
    name: '消灭魔植',
    desc: '城郊农田出现了会吃人的魔化植物，需要有经验的冒险者铲除。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.HARD,
  },
  {
    name: '护送使节',
    desc: '邻国使节需要一支可靠的护卫队伍护送他安全通过边境地区。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EPIC,
  },
  {
    name: '捕获凤凰',
    desc: '皇家法师需要捕获一只罕见的火凤凰，用于重要的魔法仪式。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.LEGENDARY,
  },
  {
    name: '教授魔法',
    desc: '魔法学院需要助教教导新学徒掌握基础魔法理论。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '破解陷阱',
    desc: '一座古老的魔法宝库被重重机关保护，需要经验丰富的解谜师破解。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.NORMAL,
  },
  {
    name: '讨伐魔犬',
    desc: '城市近郊出现了一群三头魔犬，需要勇敢的猎人将其清除。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.HARD,
  },
  {
    name: '运送秘宝',
    desc: '魔法议会需要可靠的护卫将一件危险的魔法道具送往远方的封印之地。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EPIC,
  },
  {
    name: '制服巨龙',
    desc: '一头成年火龙正在威胁边境城市，需要最顶尖的猎龙者将其制服。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.LEGENDARY,
  },
  {
    name: '教授炼药',
    desc: '药剂师行会需要经验丰富的炼药师教导学徒制作基础药剂。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '调查谋杀',
    desc: '一位商人在自己的庄园中离奇死亡，需要经验丰富的调查员查明真相。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.NORMAL,
  },
  {
    name: '除掉蛇妖',
    desc: '城郊水库出现了一条会蛊惑人心的蛇妖，需要驱魔师将其铲除。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.HARD,
  },
  {
    name: '护送皇子',
    desc: '需要一支精锐护卫队伍秘密护送皇子前往边境城堡。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EPIC,
  },
  {
    name: '封印古墓',
    desc: '一座远古魔王的陵墓出现封印松动的迹象，需要顶级法师加固封印。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.LEGENDARY,
  },
  {
    name: '教授弓术',
    desc: '猎人行会需要弓术教师指导新手猎人掌握基础箭术。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '调查邪教',
    desc: '城中出现可疑的邪教活动，需要经验丰富的调查员暗中追查。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.NORMAL,
  },
  {
    name: '猎杀石像鬼',
    desc: '古堡顶部的石像鬼突然活了过来，需要勇士将其消灭。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.HARD,
  },
  {
    name: '运送圣器',
    desc: '教会需要可靠的护卫队伍护送一件强大的圣器穿越魔物横行的区域。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.EPIC,
  },
  {
    name: '镇压魔神',
    desc: '一位远古魔神即将破除封印，需要最强大的法师前往镇压。',
    quality: QualityLevel.E,
    difficulty: MissionDifficulty.LEGENDARY,
  },
];
