/* eslint-disable import/prefer-default-export */
import { MissionDifficulty, QualityLevel } from '../enums';
import { MissionInfo } from '../mission/Mission';

export const missionsInfo: MissionInfo[] = [
  {
    name: '清理老鼠',
    desc: '酒馆地窖里出现了一群老鼠，它们正在破坏储存的食物。需要有人帮忙清理。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '采集药草',
    desc: '药剂师需要一些常见的药用植物，这些植物生长在镇子附近的草地上。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '驱赶野兔',
    desc: '农夫的菜园被野兔侵扰，需要帮忙驱赶这些调皮的小家伙。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '捕捉流浪猫',
    desc: '城市管理员需要有人帮忙捕捉并安置街上的流浪猫，要求对待动物要温柔。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '协助织布',
    desc: '织布工坊需要帮手整理原料和清洁织布机，工作轻松但要细心。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '搬运石料',
    desc: '石匠需要帮手将石料从采石场运到工作坊，体力活。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '照看孤儿',
    desc: '教会孤儿院的修女生病了，需要人手帮忙照看孤儿一天。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '清点药材',
    desc: '药剂师需要帮手整理和清点药材库存，要求认识基础药材。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '维护路灯',
    desc: '城市守卫需要人手检查和更换街道上的油灯，确保夜晚照明。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '打磨工具',
    desc: '铁匠铺需要帮工打磨一批生锈的工具，工作简单但费时。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '晾晒谷物',
    desc: '农户需要帮手将收获的谷物摊开晾晒，并注意天气变化。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '清理花园',
    desc: '旅店的小花园需要修剪杂草，整理花木。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '分类废料',
    desc: '铁匠铺需要将废弃的金属材料分类整理，为回炉做准备。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '看守货摊',
    desc: '水果摊主需要临时外出，需要人手看管摊位一个时辰。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '整理皮毛',
    desc: '皮革店需要将新到的兽皮分类存放，要求轻拿轻放。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '照料盆栽',
    desc: '花店需要帮手给各类盆栽浇水施肥，工作轻松但要细心。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '擦拭器具',
    desc: '武器店需要人手清洁和擦拭展示用的武器，要求小心谨慎。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '引水灌溉',
    desc: '菜农需要帮手将河水引入菜地进行灌溉。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '叠放货物',
    desc: '布庄需要将新到的布匹整齐叠放在货架上。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EASY,
  },
  {
    name: '迷宫探索',
    desc: '一处古老地下迷宫被发现，需要帮手绘制地图和记录路线。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.NORMAL,
  },
  {
    name: '守卫矿井',
    desc: '采矿场需要守卫帮忙看守矿井入口，防止盗矿者。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.NORMAL,
  },
  {
    name: '引导商队',
    desc: '一支外地商队需要向导带领他们穿过城市复杂的街道。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.NORMAL,
  },
  {
    name: '追踪野兽',
    desc: '猎人需要帮手在森林中追踪一头受伤的野鹿。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.HARD,
  },
  {
    name: '深井打捞',
    desc: '一位商人不小心将重要的钥匙掉入深井，需要人手打捞。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.HARD,
  },
  {
    name: '山洞探查',
    desc: '城郊发现一个神秘山洞，需要胆大的探险者进行初步探查。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EPIC,
  },
  {
    name: '驯服野狗',
    desc: '一只特别凶猛的野狗需要被驯服，它经常在市场偷东西。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EPIC,
  },
  {
    name: '沼泽采药',
    desc: '一种珍贵的药草生长在危险的沼泽地带，需要冒险者前去采集。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.LEGENDARY,
  },
  {
    name: '古井探索',
    desc: '一口古井传出奇怪的声音，需要勇敢的人下去查看究竟。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.LEGENDARY,
  },
  {
    name: '诡异捕鼠',
    desc: '地窖里出现了一群异常聪明的老鼠，普通的陷阱都无法捕获。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.LEGENDARY,
  },
  {
    name: '寻找宝石',
    desc: '一位矿工在矿洞中发现了宝石的痕迹，需要帮手在安全区域继续寻找。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.NORMAL,
  },
  {
    name: '探索密室',
    desc: '老宅翻修时发现了一个隐藏的地下室，需要帮手协助调查。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.NORMAL,
  },
  {
    name: '捉捕海鱼',
    desc: '渔民发现了一处新的渔场，需要帮手尝试新的捕鱼方式。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.NORMAL,
  },
  {
    name: '夜间巡逻',
    desc: '城郊农场遭遇多起偷盗事件，需要夜间巡逻人手。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.HARD,
  },
  {
    name: '危险运输',
    desc: '需要将一车易碎的陶器通过崎岖山路运送到邻镇。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.HARD,
  },
  {
    name: '洞穴测绘',
    desc: '矿工在山中发现了新的矿洞，需要勇敢的测绘员绘制地图。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EPIC,
  },
  {
    name: '驯服野马',
    desc: '牧场抓到了一匹性格暴躁的野马，需要有经验的人来驯服。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EPIC,
  },
  {
    name: '幽灵调查',
    desc: '古老钟楼每到午夜就传出怪声，需要胆大的人彻夜调查。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.LEGENDARY,
  },
  {
    name: '捕捉巨蛇',
    desc: '农田里出现了一条体型异常的大蛇，需要捕捉并转移。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.LEGENDARY,
  },
  {
    name: '探索陵墓',
    desc: '考古学者发现了一处未开发的古代陵墓，需要帮手协助初步勘探。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.LEGENDARY,
  },
  {
    name: '寻找宝石',
    desc: '一位矿工在矿洞中发现了宝石的痕迹，需要帮手在安全区域继续寻找。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.NORMAL,
  },
  {
    name: '探索密室',
    desc: '老宅翻修时发现了一个隐藏的地下室，需要帮手协助调查。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.NORMAL,
  },
  {
    name: '捉捕海鱼',
    desc: '渔民发现了一处新的渔场，需要帮手尝试新的捕鱼方式。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.NORMAL,
  },
  {
    name: '夜间巡逻',
    desc: '城郊农场遭遇多起偷盗事件，需要夜间巡逻人手。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.HARD,
  },
  {
    name: '危险运输',
    desc: '需要将一车易碎的陶器通过崎岖山路运送到邻镇。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.HARD,
  },
  {
    name: '洞穴测绘',
    desc: '矿工在山中发现了新的矿洞，需要勇敢的测绘员绘制地图。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EPIC,
  },
  {
    name: '驯服野马',
    desc: '牧场抓到了一匹性格暴躁的野马，需要有经验的人来驯服。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.EPIC,
  },
  {
    name: '幽灵调查',
    desc: '古老钟楼每到午夜就传出怪声，需要胆大的人彻夜调查。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.LEGENDARY,
  },
  {
    name: '捕捉巨蛇',
    desc: '农田里出现了一条体型异常的大蛇，需要捕捉并转移。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.LEGENDARY,
  },
  {
    name: '探索陵墓',
    desc: '考古学者发现了一处未开发的古代陵墓，需要帮手协助初步勘探。',
    quality: QualityLevel.F,
    difficulty: MissionDifficulty.LEGENDARY,
  },
];
